title: rishi athavale
description: "eecs @ berkeley, researcher @ bair"
url: https://rishipython.github.io

# stick to the built-in pinned theme FIRST so we know it deploys
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed

# top nav
header_pages:
  - projects.md
  - experience.md
  # - education.md
  # - skills.md

markdown: kramdown
kramdown:
  input: GFM
